modified:   ../healthchecks/embycheck	updated mount check 	modified:   ../healthchecks/plexcheck	updated mount check

diff --git a/healthchecks/plexcheck b/healthchecks/plexcheck
--- a/healthchecks/plexcheck
+++ b/healthchecks/plexcheck
@@ -24,8 +24,14 @@ fi
 mountpoint ${MOUNT}
 if [[ ${?} -ne  0 ]];
 then
-	echo $(date) - ${APP} - Rclone mount failed >> ${LOG}
-	exit 2			# Rclone mount failed
+	echo $(date) - ${APP} - OmniMount failed >> ${LOG}
+	exit 2			# OmniMount failed
+fi
+
+if [[ -f ${MEDIA}/omnimounted ]];
+then
+	echo $(date) - ${APP} - Media failure >> ${LOG}
+	exit 3			# External mapping present but no cloud
 fi
 
 exit 0
