modified:   bin/menu	fixed exit status 	new file:   bin/update	system update added to OmniStream 	modified:   bin/utilities	expanded utilities

diff --git a/bin/utilities b/bin/utilities
--- a/bin/utilities
+++ b/bin/utilities
@@ -2,7 +2,7 @@
 
 hash dialog 2>/dev/null || { echo Installing dialog \(one time\) ; sudo apt update > /dev/null ; sudo apt install dialog -y > /dev/null ; }
 source ${HOME}/.config/omnistream.conf
-source ${HOME}/Omni/bin/omni_functions
+source ${HOME}/OmniStream/bin/omni_functions
 
 DIALOG_CANCEL=1
 DIALOG_ESC=255
@@ -10,68 +10,85 @@ HEIGHT=0
 WIDTH=0
 
 display_result() {
-  dialog --title "${1}" \
-    --no-collapse \
-    --msgbox "$result" 0 0
+	dialog --title "${1}" \
+		--no-collapse \
+		--msgbox "$result" 0 0
 }
 
 program_runner() {
 	${1} 2>&1 | dialog --programbox 1000 1000
 }
 
-while true; do
-  exec 3>&1
-  SELECTION=$(dialog \
-    --backtitle "Omni Controls" \
-    --title "Menu" \
-    --no-tags \
-    --clear \
-    --cancel-label "Exit" \
-    --menu "Please select:" ${HEIGHT} ${WIDTH} 5 \
-    "1" "rclean - Reset everything" \
-    "2" "omni up - refresh containers and bring up new ones" \
-    "3" "omni down - take down all containers; leave mounts" \
-    "4" "omni fullstop - take down everything inc. mounts" \
-    "5" "omni update - update all running Omni containers" \
-    "6" "omni status - show the status of running containers" \
-    "7" "update - run updates for operating system" \
-    2>&1 1>&3)
-  EXIT_STATUS=${?}
-  exec 3>&-
-  case ${EXIT_STATUS} in
-    ${DIALOG_CANCEL})
-      clear
-      echo "Program terminated."
-      exit
-      ;;
-    ${DIALOG_ESC})
-      clear
-      echo "Program aborted." >&2
-      exit 1
-      ;;
-  esac
-  case ${SELECTION} in
-    1 )
-      rclean
-      ;;
-    2 )
-      omni up
-      ;;
-    3 )
-      omni down
-      ;;
-    4 )
-      omni fullstop
-      ;;
-    5 )
-      program_runner "omni update"
-      ;;
-    6 )
-      result=$(omni status)
-      display_result "Omni Status"
-      ;;
-    7 )
-      program_runner update
-      ;;
-  esac
+while true
+do
+	exec 3>&1
+	SELECTION=$(dialog \
+		--backtitle "Omni Controls" \
+		--title "Menu" \
+		--no-tags \
+		--clear \
+		--cancel-label "Exit" \
+		--default-item "${SELECTION}" \
+		--menu "Please select:" ${HEIGHT} ${WIDTH} 5 \
+		"1" "omni up - refresh containers and bring up new ones" \
+		"2" "omni down - take down all containers; leave mounts" \
+		"3" "omni restart - restart all containers" \
+		"4" "omni update - update all running Omni containers" \
+		"5" "omni status - show the status of running containers" \
+		"6" "omni stats - show realtime stats (ctrl-c to exit" \
+		"7" "omni repair - force update OmniStream to latest version" \
+		"8" "dns report - show a report of DNS entries for active containers" \
+		"9" "update - run updates for operating system" \
+		2>&1 1>&3)
+	EXIT_STATUS=${?}
+	exec 3>&-
+	case ${EXIT_STATUS} in
+		${DIALOG_CANCEL})
+			clear
+			echo "Program terminated."
+			exit
+			;;
+		${DIALOG_ESC})
+			clear
+			echo "Program aborted." >&2
+			exit 1
+			;;
+	esac
+	case ${SELECTION} in
+		1 )
+			clear
+			omni up
+			;;
+		2 )
+			clear
+			omni down
+			;;
+		3 )
+			clear
+			omni restart
+			;;
+		4 )
+			clear
+			omni update
+			;;
+		5 )
+			result=$(omni status)
+			display_result "Omni Status"
+			;;
+		6 )
+			program_runner "Omni stats"
+			;;
+		7 )
+			clear
+			omni repair
+			;;
+		8 )
+			dns-report-gen
+			result=$(cat "${OMNIHOME}/dns-report.txt")
+			display_result "DNS Report"
+			;;
+		9 )
+			program_runner update
+			;;
+	esac
 done
